### References
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjgyODYyODl9.J4Cm7M2Dwdb6vtUChGBE7iASvMsDS8XMpFcr8cSd2as


### Users Actions --------------------------------------------
### Index
GET http://localhost:3000/users.json

### Show
GET http://localhost:3000/users/1.json
Authorization: Bearer {{jwt}}

### Create
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "new user test",
  "email": "test@email.com",
  "avatar": "https://avataaars.io/?avatarStyle=Circle&topType=LongHairStraight&accessoriesType=Blank&hairColor=Black&facialHairType=Blank&clotheType=Hoodie&clotheColor=Blue03&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Light",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions Actions ------------------------------------------
### Create
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "mark@email.com",
  "password": "password"
}

### Snapshots Actions -----------------------------------------
### Index
GET http://localhost:3000/snapshots.json
Authorization: Bearer {{jwt}}

### Show
GET http://localhost:3000/snapshots/37.json
Authorization: Bearer {{jwt}}

### Create
POST http://localhost:3000/snapshots.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "new snapshot test",
  "start_date": "2016-03-23",
  "end_date": "2016-09-27",
  "image": "image.url",
  "artists": ["artist 1", "artist 2"],
  "tracks": ["track 1", "track"]
}

### Update
PATCH http://localhost:3000/snapshots/8
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "lol updated title!",
  "image": "updated image.url"
}

### Destroy
DELETE http://localhost:3000/snapshots/
Authorization: Bearer {{jwt}}


### Artists Actions ------------------------------------------
### Index
GET http://localhost:3000/artists.json
Authorization: Bearer {{jwt}}

### Show
GET http://localhost:3000/artists/1.json
Authorization: Bearer {{jwt}}

### Create
POST http://localhost:3000/artists
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "a 2nd artist",
  "image": "image.url",
  "snapshot_id": 1

}

### Destroy
DELETE http://localhost:3000/artists/8
Authorization: Bearer {{jwt}}

### Songs Actions -------------------------------------
### Index
GET http://localhost:3000/songs
Authorization: Bearer {{jwt}}

### Show
GET http://localhost:3000/songs/1
Authorization: Bearer {{jwt}}

### Create
POST http://localhost:3000/songs
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "a 4th?? song",
  "artist": "artist name lol",
  "album": "album title",
  "album_art": "image.url",
  "snapshot_id": 1
}

### Destroy
DELETE http://localhost:3000/songs/4
Authorization: Bearer {{jwt}}

### Genres Actions ------------------------------------------
### Index
GET http://localhost:3000/genres
Authorization: Bearer {{jwt}}

### Show
GET http://localhost:3000/genres/1
Authorization: Bearer {{jwt}}

### Create
POST http://localhost:3000/genres
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "another genre",
  "snapshot_id": 1
}

### Destroy
DELETE http://localhost:3000/genres/6
Authorization: Bearer {{jwt}}