### References
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2Njc5NDY4MDJ9.vrI1nGGEWZHTwqBKfxXi02jPR3togyWx_xqWSz9ee_0


### Users Actions --------------------------------------------
### Index
GET http://localhost:3000/users

### Create
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "new user test",
  "email": "test@email.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions Actions ------------------------------------------
### Create
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "password"
}

### Snapshots Actions -----------------------------------------
### Index
GET http://localhost:3000/snapshots
Authorization: Bearer {{jwt}}

### Show
GET http://localhost:3000/snapshots/2
Authorization: Bearer {{jwt}}

### Create
POST http://localhost:3000/snapshots
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "new snapshot test",
  "start_date": "2016-03-23",
  "end_date": "2016-09-27",
  "image": "image.url"
}

### Update
PATCH http://localhost:3000/snapshots/7
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "lol updated title!",
  "image": "updated image.url"
}

### Destroy
DELETE http://localhost:3000/snapshots/7
Authorization: Bearer {{jwt}}
