### References
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Njc5NTA1Mzd9.hn7hvlk3rJh8zd07RRhOnmVUSyWir4PZ-zriE1Xbiug


### Users Actions --------------------------------------------
### Index
GET http://localhost:3000/users

### Create
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "new user test",
  "email": "test@email.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions Actions ------------------------------------------
### Create
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "mark@email.com",
  "password": "password"
}

### Snapshots Actions -----------------------------------------
### Index
GET http://localhost:3000/snapshots
Authorization: Bearer {{jwt}}

### Show
GET http://localhost:3000/snapshots/1
Authorization: Bearer {{jwt}}

### Create
POST http://localhost:3000/snapshots
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "new snapshot test",
  "start_date": "2016-03-23",
  "end_date": "2016-09-27",
  "image": "image.url"
}

### Update
PATCH http://localhost:3000/snapshots/8
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "lol updated title!",
  "image": "updated image.url"
}

### Destroy
DELETE http://localhost:3000/snapshots/8
Authorization: Bearer {{jwt}}


### Artists Actions ------------------------------------------
### Index
GET http://localhost:3000/snapshots/1/artists
Authorization: Bearer {{jwt}}

### Show
GET http://localhost:3000/snapshots/1/artists/1
Authorization: Bearer {{jwt}}

### Create
POST http://localhost:3000/snapshots/1/artists
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "a 2nd artist",
  "image": "image.url"
}

### Destroy
DELETE http://localhost:3000/snapshots/1/artists/8
Authorization: Bearer {{jwt}}

### Songs Actions -------------------------------------
### Index
GET http://localhost:3000/snapshots/1/songs
Authorization: Bearer {{jwt}}

### Show
GET http://localhost:3000/snapshots/1/songs/1
Authorization: Bearer {{jwt}}

### Create
POST http://localhost:3000/snapshots/1/songs
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "a 4th?? song",
  "artist": "artist name lol",
  "album": "album title",
  "album_art": "image.url",
  "snapshot_id": 1
}

### Destroy
DELETE http://localhost:3000/snapshots/1/songs/4
Authorization: Bearer {{jwt}}

### Genres Actions ------------------------------------------
### Index
GET http://localhost:3000/snapshots/1/genres
Authorization: Bearer {{jwt}}

### Show
GET http://localhost:3000/snapshots/1/genres/1
Authorization: Bearer {{jwt}}

### Create
POST http://localhost:3000/snapshots/1/genres
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "another genre",
  "snapshot_id": 1
}

### Destroy
DELETE http://localhost:3000/snapshots/1/genres/6
Authorization: Bearer {{jwt}}